### ISSUE TITLE
do not need create own .jar

### ISSUE THREAD

**Issue by cutebear0123** [ItzMiracleOwO/WardDashboard#3]
do not need create own .jar
i do not like to install a java IDE for a app

**Comment by ItzMiracleOwO** [comment]
Using a .jar file is another choice for the users, u can also use `Docker Desktop` to build and deploy the app!
For simplifying the process of deploying, we will put the .jar file in the `version` page soon!

**Comment by ItzMiracleOwO** [comment]
It seem that our .jar file is buggy, we are looking into it and will be fixed soon!

**Comment by cutebear0123** [comment]
thank ;)
